### ISSUE TITLE
Use ES6 string template literals

### ISSUE THREAD

**Issue by mgwalker** [18F/bpa-trello#19]
If we're going to use ES6, we can also use template strings and let the engine handle interpolation for us instead of having a custom function for it.

E.g., instead of:

`'My name is {n}'.supplant({ n: 'Greg' })`
(which is really pretty, btw)

We could have:

`` `My name is ${name}` ``

Using backticks instead of single/double quotes.

**Comment by lauraGgit** [comment]
Closed by #38
