### ISSUE TITLE
Account for federal holidays

### ISSUE THREAD

**Issue by mgwalker** [18F/bpa-trello#39]
In addition to business days, also account for US federal holidays.

See:
https://github.com/18f/us-federal-holidays
https://www.npmjs.com/package/@18f/us-federal-holidays

You can plug those dates right into [moment-business-days](https://www.npmjs.com/package/moment-business-days).  E.g.:

```
var moment = require('moment-business-days');
var fedHolidays = require('@18f/us-federal-holidays');
var holidays = fedHolidays.allForYear(2016);

moment.locale('us', {
    holidays: holidays.map(function(h) { return h.dateString; }),
    holidayFormat: 'YYYY-M-DD
});
```

(**Note:** That code isn't tested, just off-the-cuff.)

**Comment by lauraGgit** [comment]
Closed by #44
